services:
  - type: web
    name: jobika-backend
    env: python
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:23110081aiiTgn@db.eabkwiklxjbqbfxcdlkk.supabase.co:5432/postgres
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://jobika-backend.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.5

